geometry_msgs/Polygon[] new_objects # List of polygons representing an object
geometry_msgs/Point32[] points_objects_to_remove # List of points where to remove objects
bool is_robot_relative false # Whether the coordinates are relative to the robot position
---
