head_node:
  ros__parameters:
    action_manager_period: 0.5
    sequence_default_filename: "demo_seq.json"
    global_frame_id: "map"
    start_actions_topic: "/can_start_actions"
    stop_time: 99.0
    use_sim_time: true
