head_node:
  ros__parameters:
    action_manager_period: 0.5
    sequence_default_filename: "demo_seq.json"
    blue_sequence_file: ""
    yellow_sequence_file: ""
    team_colors: ["blue", "yellow"]
    global_frame_id: "map"
    start_actions_topic: "/can_start_actions"
    restart_topic: "/restart"
    stop_time: 99.0
    time_to_enable_laser_sensors: 85.0
    use_sim_time: true
