name: ROS2 test packages

on:
  push:
    branches: [ "master" ]
    paths:
      - 'robot/ros_ws/**'
      - '!**.md'
      - '!**.png'
      - '!robot/ros_ws/src/herminebot_head/sequences/*'
  pull_request:
    paths:
      - 'robot/ros_ws/**'
      - '!**.md'
      - '!**.png'
      - '!robot/ros_ws/src/herminebot_head/sequences/*'

jobs:
  build_and_test:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4 # Checkout the repository

      # Install some system packages
      - name: Install ROS 2 Jazzy packages
        run: |
          chmod +x scripts/ros2_project_install.sh
          sudo ./scripts/ros2_project_install.sh --no-cleanup

      - name: Install Python modules
        run: |
          cd robot/ros_ws
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          deactivate

      # Build for test coverage
      - name: Configure CMake flags and build executables
        run: |
          cd robot/ros_ws
          source /opt/ros/jazzy/setup.bash
          colcon build --packages-select hrc_interfaces
          source install/setup.bash
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} --coverage -DGITHUB_ACTION" --packages-ignore hrc_interfaces
          # hrc_interfaces should not be included in lcov as it is fully autogenerated
          lcov --no-external --capture --initial --ignore-errors mismatch,mismatch,gcov --directory . --output-file ros2_base.info

      - name: Run tests and generate python coverage
        timeout-minutes: 1 # Avoid to be stuck in infinite loop
        run: |
          source /opt/ros/jazzy/setup.bash
          cd robot/ros_ws
          source install/setup.bash
          # The argument '--retest-until-pass' allows to reduce the probability of having false error
          colcon test --return-code-on-test-failure --pytest-with-coverage --retest-until-pass 5

      - name: Show test results
        if: failure()
        timeout-minutes: 1 # Avoid to be stuck printing value from an infinite loop
        run: |
          source /opt/ros/jazzy/setup.bash
          cd robot/ros_ws
          source install/setup.bash
          colcon test-result --all --verbose

      - name: Generate C++ code coverage
        if: success()
        run: |
          cd robot/ros_ws
          lcov --no-external --capture --ignore-errors mismatch,mismatch,gcov --directory . --output-file ros2.info
          lcov --add-tracefile ros2_base.info --add-tracefile ros2.info --output-file ros2_coverage.info
          lcov --extract ros2_coverage.info '*/src/*' --output-file ros2_coverage_filtered.info  # Only source files

      - name: Upload coverage result to CodeCov
        if: success()
        uses: codecov/codecov-action@v5
        with:
          files: ${{github.workspace}}/robot/ros_ws/ros2_coverage_filtered.info,${{github.workspace}}/robot/ros_ws/build/*/coverage.xml
          # flags: unittests # optional
          disable_search: true
          # name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
